language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - |
    if [ ! -d flutter ] ; then
      git clone https://github.com/flutter/flutter.git -b beta
    fi
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - flutter
    - $HOME/.pub-cache