name: vcr
description: A package to mock requests in tests, storing request in json files and reusing
version: 0.2.0
homepage: https://github.com/louis-kevin/vcr

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
